import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { CiCirclePlus } from "react-icons/ci";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html className='bg-[#182d56]' lang="en">
      <body className="w-1/3 px-8 border-x-1 bg-white h-screen border-black mx-auto">
        <header className="flex justify-between py-6 border-b-1 border-black items-center">
          <h1>POSTS</h1>
          <CiCirclePlus size={23} />
        </header>
        {children}
      </body>
    </html>
  );
}
