import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { FaHome, FaRegUser } from "react-icons/fa";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html className="bg-[#182d56]" lang="en">
      <body
        cz-shortcut-listen="true"
        className="w-1/3 px-8 border-x-1 bg-white h-screen border-black mx-auto"
      >
        <header className="flex justify-between py-6 border-b-1 border-black items-center">
          <h1 className="font-bold text-2xl italic">PERSONAL BLOG</h1>
          <div className='flex gap-4'>
            <Link href={"/"}>
              <FaHome size={23} />
            </Link>
            <Link href={"/admin"}>
              <FaRegUser size={23} />
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
